### ISSUE TITLE
Must have arb file support

### ISSUE THREAD

**Issue by dalewking** [defuncart/flutter_pseudolocalizor#8]
Now that Flutter localization is based around arb files, only supporting CSV files, makes this unusable.

**Comment by defuncart** [comment]
@dalewking Even when the package was launched 18 months ago, ARB was already the default localization solution, however arb support wasn't something I personally needed until now.

I recently started working on [feature/arb-file-support](https://github.com/defuncart/flutter_pseudolocalizor/tree/feature/arb-file-support) in which a very basic POC is already working. Will report back to this issue once more progress has been made.

**Comment by dalewking** [comment]
That should get me started, but would be much better to support generating multiple languages. I actually started coding something up then realized I could probably write a wrapper for your library that would do it, but now I won't bother.

**Comment by defuncart** [comment]
@dalewking As of now, replacing base language in arb works well in [feature/arb-file-support](https://github.com/defuncart/flutter_pseudolocalizor/tree/feature/arb-file-support). Ability to generate multiple languages will come, however some prior breaking changes work like supplying output directory will firstly need to be done. 

For now, if you need multiple arb files (i.e. intl_de.arb etc.), you could firstly generate arb with pseudo texts replacing base

```yaml
flutter_pseudolocalizor:
  input_filepath: "lib/l10n/intl_en.arb"
  output_filepath: "lib/l10n_pseudo/intl_en.arb"
  replace_base: true
```

and then duplicate `lib/l10n_pseudo/intl_en.arb`, replacing en with de etc.

**Comment by defuncart** [comment]
@dalewking [feature/arb-file-support](https://github.com/defuncart/flutter_pseudolocalizor/tree/feature/arb-file-support) has been updated to support both replacing base language, and generating arb files for specified languages. Please see [README](https://github.com/defuncart/flutter_pseudolocalizor/tree/feature/arb-file-support#getting-started) for more details.

**Comment by defuncart** [comment]
Arb file support is now merged into main. Version 0.5.0 will be released over the coming weeks as I'd like to look into Latin Extended-B etc. Leaving issue open until 0.5.0 is released. In the meantime, please use

```yml
dev_dependencies:
  flutter_pseudolocalizor:
    git:
      url: https://github.com/defuncart/flutter_pseudolocalizor
      ref: main
```
